---
 - hosts: "{{ servidores }}"
   handlers:
     - name: reinicio apache
       win_service:
         name: Apache2.2 
         state: restarted 
       listen: "restart web"
   tasks:
      - name: Modificamos mail ServerAdmin
        win_lineinfile:
          path: C:\Program Files (x86)\Apache Software Foundation\Apache2.2\conf\httpd.conf
          regex: '^ServerAdmin'
          line: 'ServerAdmin borja@windows.com'
        notify: "restart web"