---
 - hosts: "{{ servidores }}"
   gather_facts: false
   tasks:
     - name: Verificar conexión WEB a localhost
       win_uri:
         url: "http://localhost"
       ignore_errors: true
     - name: Muestra el mensaje si ha ido bien o no
       debug:
         msg: "Ha funcionado!!"