---
- hosts: "{{ servidores }}"
  tasks:
      - name: creamos directorio C:\Temp\prueba_when
        win_file: 
          path: C:\Temp\prueba_when
          state: directory
        when: ansible_ip_addresses[0] == "192.168.17.203"