---
- hosts: "{{ servidores }}"
  tasks:
    - name: creamos directorio de apache 
      win_file:
        path: C:\Temp
        state: directory
      tags: config
    - name: Descargamos instalador de apache
      win_get_url:
        url: https://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-no_ssl.msi
        dest: C:\Temp
      tags: config
    - name: Instalamos MSI de apache
      win_package:
        path: 'C:\Temp\httpd-2.2.25-win32-x86-no_ssl.msi'
        state: present
      tags: install
    - name: configuramos mail serveradmin
      win_lineinfile:
        path: C:\Program Files (x86)\Apache Software Foundation\Apache2.2\conf\httpd.conf
        regex: '^ServerAdmin'
        line: 'ServerAdmin borja@windows.com'
      tags: config
    - name: Creamos página de apache
      win_copy:
        dest: C:\Program Files (x86)\Apache Software Foundation\Apache2.2\htdocs\index.html
        content: |
          <html>
          <meta charset=UTF-8>
          <body>
          <h1>Bienvenido a la página de apache de MINECO</h1>
          Bienvenido a la página de MINECO
          Funciona correctamente
          Hasta luego
          </body>
          </html>
        tags: config 
    - name: verificamos si Apache2.2 existe
      win_service:
        name: Apache2.2 
      register: apache_service
      tags: config
    - name: Creamos el servicio de apache
      win_shell: '"C:\Program Files (x86)\Apache Software Foundation\Apache2.2\bin\httpd.exe" -k install'
      args:
        executable: cmd
      when: not apache_service.exists
      tags: config
    - name: Iniciamos el servicio Apache2.2 
      win_service:
        name: Apache2.2 
        state: started
        tags: config
    - name: Desinstalamos apache
      win_package:
        path: 'C:\Temp\httpd-2.2.25-win32-x86-no_ssl.msi'
        state: absent
      tags: [ uninstall, never ]         
    - name: Abrimos el puerto 80
      win_firewall_rule:
        name: HTTP
        localport: 80
        action: allow
        direction: in
        protocol: tcp
        state: present
        enabled: yes
      tags: [ uninstall, never ]
